### ISSUE TITLE
Add scheduled payment

### ISSUE THREAD

**Issue by MakMuftic** [NodeFactoryIo/vedran#123]

**Comment by MakMuftic** [comment]
@mpetrun5 @mpetrunic How should we handle the scheduling of payment execution? 

Should it be a monthly action? Maybe have some scheduled job that checks if a month has passed after the last payment?

**Comment by mpetrunic** [comment]
LB operator should choose payout interval. Could be monthy, querterly, every 15days. Maybe it's best to allow lb operator to enter payout interval in days?
