### ISSUE TITLE
Ping request endpoint

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/vedran#3]
- http
- auth using token in header (X-Auth-Header) 
- `POST /api/v1/nodes/{id}/pings`

- implementation:
   - store ping timestamp for given node id

**Comment by mpetrun5** [comment]
@mpetrunic @MakMuftic 
I forgot to ask. I changed the url on daemon to /api/v1/nodes/pings as we should have node-id in token.
Is that ok or should I change?

**Comment by mpetrunic** [comment]
Yup, thats fine.
