### ISSUE TITLE
Metrics request endpoint

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/vedran#4]
- http
- auth using token in x-Auth-Header
- `PUT api/v1/nodes/{id}/metrics`
- body:
```
peer_count: number,
best_block_height: number,
finalized_block_height: number,
ready_transactions_count: number
```
- impl:
   - update data for given node id

**Comment by MakMuftic** [comment]
@mpetrun5 I followed the same logic here by removing id from URL (as this information is saved inside auth token)

**Comment by mpetrun5** [comment]
> @mpetrun5 I followed the same logic here by removing id from URL (as this information is saved inside auth token)

:+1:
